name: SonarCloud
on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/openatv/enigma2-buildenv/enigma2-buildenv:latest
      options: --user root
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install sonar-scanner + build-wrapper
        run: |
          export SONAR_SCANNER_VERSION=5.0.1.3006
          export BUILD_WRAPPER_VERSION=6.0.0.4432

          curl -sSLo sonar-scanner.zip "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip"
          unzip sonar-scanner.zip -d /opt
          export PATH="/opt/sonar-scanner-$SONAR_SCANNER_VERSION-linux/bin:$PATH"

          curl -sSLo build-wrapper.zip "https://binaries.sonarsource.com/CommercialDistribution/build-wrapper-linux-x86/build-wrapper-linux-x86-$BUILD_WRAPPER_VERSION.zip"
          unzip build-wrapper.zip -d /opt
          export PATH="/opt/build-wrapper-linux-x86-$BUILD_WRAPPER_VERSION:$PATH"

          echo "$PATH"

      - name: Run build-wrapper
        env:
          CC: "gcc-14"
          CXX: "g++-14"
        run: |
          sed -i 's/include lib main data po tools/include lib main tools/g' Makefile.am
          autoreconf -i
          export LIBS="-L/usr/lib/x86_64-linux-gnu -lpython3.13"
          export CPPFLAGS="-I/usr/include/python3.13"
          ./configure PYTHON=python3.13 --with-libsdl=no --with-boxtype=nobox --enable-dependency-tracking ac_cv_prog_c_openmp=-fopenmp --with-gstversion=1.0 --with-textlcd
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} make

      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json" \
            -Dsonar.verbose=true
