name: SonarCloud

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/openatv/enigma2-buildenv/enigma2-buildenv:latest
      options: --user root
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory

    steps:
      # 1️⃣ Checkout Repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 3️⃣ Install Build Wrapper Manuell
      - name: Download and prepare build-wrapper
        run: |
          BW_VERSION=6.0.0.4432
          curl -sSLo build-wrapper.zip "https://binaries.sonarsource.com/CommercialDistribution/build-wrapper-linux-x86/build-wrapper-linux-x86-$BW_VERSION.zip"
          unzip build-wrapper.zip -d $HOME/build-wrapper
          chmod +x $HOME/build-wrapper/build-wrapper-linux-x86-64
          echo "Build wrapper ready at $HOME/build-wrapper/build-wrapper-linux-x86-64"

      # 4️⃣ Run Build mit Build Wrapper
      - name: Run build-wrapper
        env:
          CC: "gcc-14"
          CXX: "g++-14"
        run: |
          sed -i 's/include lib main data po tools/include lib main tools/g' Makefile.am
          autoreconf -i
          export LIBS="-L/usr/lib/x86_64-linux-gnu -lpython3.13"
          export CPPFLAGS="-I/usr/include/python3.13"
          ./configure PYTHON=python3.13 --with-libsdl=no --with-boxtype=nobox --enable-dependency-tracking ac_cv_prog_c_openmp=-fopenmp --with-gstversion=1.0 --with-textlcd

          BUILD_WRAPPER="$HOME/build-wrapper/build-wrapper-linux-x86-64"
          "$BUILD_WRAPPER" --out-dir "${BUILD_WRAPPER_OUT_DIR}" make

      # 5️⃣ Run SonarCloud Scan
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.cfamily.compile-commands=${BUILD_WRAPPER_OUT_DIR}/compile_commands.json
            -Dsonar.verbose=true
